### ISSUE TITLE
Heroku Connection Refused

### ISSUE THREAD

**Issue by butchewing** [kroketio/quart-session#13]
Are you aware of anything that would cause the following error on Heroku?

`ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)`

**Comment by kroketio** [comment]
quart-session tries to connect to `127.0.0.1:6379` but in your case it cannot. I am not familiar with Heroku but you can investigate where/how Redis is installed there. If Heroku runs Redis on a non-standard port then set the correct config: `app.config['SESSION_URI'] = ...` as per README.

I run on bare-metal and can just install Redis at which point ill have `127.0.0.1:6379` available.

**Comment by butchewing** [comment]
Oh, wow. Thank you! I knew that it was something obvious. I mistakenly had `app.config['REDIS_URL']` like an idiot. 🤦‍♂️
