### ISSUE TITLE
Some Key/Values are not being saved in Redis

### ISSUE THREAD

**Issue by butchewing** [kroketio/quart-session#14]
I have a background task that takes input from the user and then creates various key/value pairs based on the content of the input. Everything is working well, except some of the key/values are not being stored in Redis.

```
# Working properly
deduced_name = await Extract.deduce("user_name", user_message)
session['deduced_name'] = deduced_name

# Does not save to Redis
deduced_facility = await Extract.deduce("user_facility", user_message)
session['deduced_facility'] = deduced_facility
```

In this single method, I have a total of eight key/value pairs that I'm trying to save to Redis.  Half of them are stored properly the other half are not.

I did a quick experiment to see if I could pinpoint the problem.
```
# Working properly
deduced_name = await Extract.deduce("user_name", user_message)
session['deduced_name'] = deduced_name
print("Background deduced_name", deduced_name)
print("Background session['deduced_name']", session.get('deduced_name'))

# Does not save to Redis
deduced_facility = await Extract.deduce("user_facility", user_message)
session['deduced_facility'] = deduced_facility
print("Background deduced_facility", deduced_facility)
print("Background session['deduced_facility']", session.get('deduced_facility'))
```

The print output is the following:
```
Background deduced_name John Smith
Background session['deduced_name'] John Smith
Background deduced_facility Hospital
Background session['deduced_facility'] Hospital
```

With `redis-cli monitor` I get the following:
```
1694788953.275458 [0 127.0.0.1:54070] "CLIENT" "SETINFO" "LIB-NAME" "redis-py"
1694788953.275514 [0 127.0.0.1:54070] "CLIENT" "SETINFO" "LIB-VER" "5.0.0"
1694788953.276699 [0 127.0.0.1:54070] "SETEX" "session:3763bdd0-dc7d-46c0-9233-0e5b8ffa5ff2" "2678400" "{\"_permanent\":true,\"_addr\":\"127.0.0.1\",\"deduced_name\":\"John Smith\"}"
```

It is very strange that each of the print strings return the proper values as expected even though they are not all being stored in Redis. This tells me that the Quart Session variables are getting values that are able to be used initially, but not later.

Any ideas on how I can further debug this?

**Comment by kroketio** [comment]
The code provided is incomplete and does not give me a clear picture, people generally provide a small reproducible example when reporting bugs.

**Comment by butchewing** [comment]
Inside of a `background_task` I have eight session variables that I'm trying to set and store in Redis. Half of them are working properly the other half are not.

I figured out the problem. The `background_task` must have some kind of a timeout or if finishes before the session variables are actually stored in Redis. I had originally tried to set all eight session variables in one `background_task`.  Since half of them were being set properly and stored in Redis and the other half was only being set temporarily and not stored in Redis, I decided to create eight separate `background_task`'s. It now works perfectly.

I wonder if quart-session needs to send a completion callback so that the `background_task` can know when everything is done. I'm unsure how Quart knows that a `background_task` has completed.

To reproduce this create a `background_task` that makes at least 5 database calls and set each return as a session variable to be stored in Redis. You should see that only some of the session variables were actually stored in Redis. But, if you split it out in to multiple `background_task` it should work as expected.
